apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-4-file-path-readonly-allow
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical file was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-4
  process:
    matchDirectories:
    - dir: /bin/ # need some exectuables to test
  file:
    matchDirectories:
    - dir: /dev/pts/
      recursive: true
    matchPaths:
    - path: /dev/tty
      readOnly: false
    - path: /etc/passwd
      readOnly: true
    - path: /etc/nsswitch.conf
      readOnly: true
    - path: /secret.txt # echo "test" >> /secret.txt (success)
    - path: /credentials/password # echo "test" >> /credentials/password (permission denied)
      readOnly: true
  action:
    Allow
