apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-file-allow
  namespace: multiubuntu
spec:
  severity: 5
  selector:
    matchLabels:
      container: ubuntu-3
  file:
    matchPaths:
    - path: /host/var/log/firewalld
  action:
    Allow
