on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'main'
      - 'v*'

    paths: 
      - 'KubeArmor/**'
      - 'protobuf/**'

name: Create KubeArmor releases after testing the image

jobs:
  build:
    name: Create KubeArmor Release
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout KubeArmor code
        uses: actions/checkout@v2

      - name: Setup Enviroment
        id: vars
        run: |
          if: [[ github.ref == 'refs/heads/main' ]]; then
            echo ::set-output name=tag::stable
          else
            echo ::set-output name=tag::${GITHUB_REF#refs/*/}
          fi

          ./contribution/k3s/install_k3s.sh
        
      - name: Generate KubeArmor artifacts
        run: GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/build_kubearmor.sh ${{ steps.vars.outputs.tag }}

      - name: Run KubeArmor 
        run: |
          kubectl apply -f KubeArmor/build/kubearmor-test-k3s.yaml
          while [[ $(kubectl get pods -l kubearmor-app=kubearmor -n kube-system -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do sleep 1; done
          kubectl get pods -A

      - name: Test KubeArmor
        run: |
          ./tests/test-scenarios-github.sh

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Create Release
        if: steps.check-tag.outputs.match == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true # turn this to false once release notes are automatically added
          prerelease: false
          body: |
            Note for maintainers:: Update the description with the actual release notes.

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push KubeArmor images to Docker
        run: ./KubeArmor/build/push_kubearmor.sh ${{ steps.vars.outputs.tag }}
