on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'stable'
    paths: 
      - 'KubeArmor/**'
      - 'protobuf/**'

name: KubeArmor stable release 

env: 
  STABLE_TAG: kubearmor/kubearmor:stable

jobs:
  build:
    name: Create KubeArmor Release - 18.04
    runs-on: ubuntu-18.04
    timeout-minutes: 20
    steps:
      - name: Checkout KubeArmor code
        uses: actions/checkout@v2

      - name: Generate KubeArmor artifacts
        run: GITHUB_SHA=$GITHUB_SHA ./KubeArmor/build/build_kubearmor.sh ${{ env.STABLE_TAG}}

      - name: Setup Enviroment
        run: |        
          ./contribution/k3s/install_k3s.sh

      - name: Run KubeArmor 
        run: |
          kubectl apply -f KubeArmor/build/kubearmor-test-k3s.yaml
          while [[ $(kubectl get pods -l kubearmor-app=kubearmor -n kube-system -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do sleep 1; done
          kubectl get pods -A

      - name: Test KubeArmor
        run: |
          ./tests/test-scenarios-github.sh ${{ env.STABLE_TAG}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Push KubeArmor images to Docker
        run: ./KubeArmor/build/push_kubearmor.sh ${{ env.STABLE_TAG}}
